# Generated by Django 5.1.1 on 2024-10-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_rating_count_alter_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='rating_count',
        ),
    ]
